sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 147258369
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tLtSiQQahhmNXfS59Lz
    access-key-secret: cCIKr8kgb3F3bfgUSXwGXcqDegQ7lc
    backet-name: wed-skt
  redis:
    host: localhost
    port: 6379
#    password:
    database: 0